-- services seed
INSERT INTO services (name, price, description, active, created_at) VALUES
('Internet Browsing (1 Hour)', 500, '₦500 per hour', 1, NOW()),
('Computer Training (Monthly)', 25000, 'Monthly training fee', 1, NOW()),
('Computer Appreciation Course', 15000, 'Course fee', 1, NOW()),
('Graphic Design Training', 35000, 'Course fee', 1, NOW()),
('Data Analysis Training', 50000, 'Course fee', 1, NOW()),
('Desktop Publishing', 30000, 'Course fee', 1, NOW()),
('Typing (Per Page)', 300, 'Per page', 1, NOW()),
('Printing (Black & White)', 100, 'Per page', 1, NOW()),
('Printing (Colour)', 300, 'Per page', 1, NOW()),
('Photocopy (A4)', 50, 'Per page', 1, NOW()),
('Scanning', 200, 'Per page', 1, NOW()),
('Lamination (A4)', 500, 'Per page', 1, NOW()),
('Spiral Binding', 800, 'Service', 1, NOW()),
('Passport Photograph', 2000, 'Photo', 1, NOW()),
('CV Design', 3000, 'Service', 1, NOW()),
('ID Card Design', 2500, 'Service', 1, NOW()),
('Business Card Design', 5000, 'Service', 1, NOW()),
('Banner Design', 10000, 'Service', 1, NOW()),
('Logo Design', 20000, 'Service', 1, NOW()),
('JAMB Registration', 2500, 'Excluding JAMB fees', 1, NOW()),
('WAEC Registration Assistance', 2000, 'Service', 1, NOW()),
('NECO Registration Assistance', 2000, 'Service', 1, NOW()),
('NABTEB Registration Assistance', 2000, 'Service', 1, NOW()),
('NIN Slip Printing', 300, 'Service', 1, NOW()),
('BVN Slip Printing', 300, 'Service', 1, NOW()),
('Online Job Application', 1500, 'Service', 1, NOW()),
('NYSC Registration Assistance', 2000, 'Service', 1, NOW()),
('Online Form Processing', 1500, 'Service', 1, NOW()),
('Passport Application Assistance', 5000, 'Service', 1, NOW()),
('Passport Data Page Photocopy', 100, 'Service', 1, NOW()),
('Document Editing', 500, 'Per page', 1, NOW()),
('Project Typing', 500, 'Per page', 1, NOW()),
('Project Printing & Binding', 15000, 'Service', 1, NOW()),
('Certificate Printing', 500, 'Service', 1, NOW()),
('Passport Document Scanning Package', 1000, 'Service', 1, NOW());
